Repository nextcloud/contacts, pull requests merged in 2018-02, with the labels that each got.

#471 Fix linebreaks in group list
  templates/contactFilter.html
  templates/group.html
Labels: bug

#476 Move transifex config for updated l10n script
  .tx/config
Labels: 3. to review

#481 Fixed content list css bug and full details column
  .stylelintrc
  .travis.yml
  css/_contactlist.scss
  css/_details.scss
  css/style.scss
  package.json
  templates/contactDetails.html
Labels: 3. to review, bug, design, medium, regression
