Repository nextcloud/contacts, pull requests merged in 2018-08, with the labels that each got.

#588 Search, structure and design fixes for 14
  appinfo/info.xml
  css/_contactlist.scss
  css/_details.scss
  css/_navigation.scss
  css/style.scss
  js/components/contactDetails/contactDetails_controller.js
  js/contacts-inject-14.js
  js/services/search_service.js
  templates/main.php
  templates/newContactButton.html
Labels: 3. to review, compatibility, design, high

#591 Merge of Team Popcorn Fork to upstream Vue branch
  .gitignore
  css/contacts.scss
  css/settings.scss
  js/contacts.js
  package-lock.json
  package.json
  src/components/addressBook.vue
  src/components/popoverMenu/popoverItem.vue
  src/components/settingsNavigation/addAddressBook.vue
  src/components/settingsNavigation/importContacts.vue
  src/components/settingsNavigation/shareAddressBook.vue
  src/components/settingsNavigation/sharee.vue
  src/components/settingsNavigation/sortContacts.vue
  src/store/addressbooks.js
  src/views/Contacts.vue
Labels: 2. developing, 3. to review, discussion

#595 Vue share addressbook
  css/contacts.scss
  css/settings-section.scss
  css/settings.scss
  css/settings/settings-addressbook-sharee.scss
  css/settings/settings-addressbook-shares.scss
  css/settings/settings-addressbook.scss
  package-lock.json
  package.json
  src/components/Settings/SettingsAddressbook.vue
  src/components/Settings/SettingsAddressbookShare.vue
  src/components/Settings/SettingsAddressbookSharee.vue
  src/components/Settings/SettingsNewAddressbook.vue
  src/components/Settings/SettingsSortContacts.vue
  src/services/api.js
  src/store/addressbooks.js
Labels: 3. to review
