Repository nextcloud/contacts, pull requests merged in 2018-03, with the labels that each got.

#510 MD5 invalid uids
  js/models/contact_model.js
Labels: 3. to review, bug, compatibility, medium

#511 Fixed lastName sorting
  js/dav/dav.js
  js/dav/lib/contacts.js
Labels: 3. to review, bug, high, regression

#524 Fixed contactsHeader details update
  js/components/contactDetails/contactDetails_controller.js
Labels: 3. to review, bug, high, regression

#526 fix issue #373 suppresses comma when last name sorting is selected
  js/components/contact/contact_controller.js
Labels: regression

#528 Bump version
  appinfo/info.xml
  package.json
Labels: 3. to review
