Repository nextcloud/contacts, pull requests merged in 2018-11, with the labels that each got.

#704 Disabled ab should not be suggested
  .travis.yml
  css/Properties/Properties.scss
  css/Settings/SettingsAddressbook.scss
  css/Settings/SettingsAddressbookSharee.scss
  css/Settings/SettingsAddressbookShares.scss
  css/SettingsSection.scss
  css/icons.scss
  img/address-book.svg
  src/components/ContactDetails.vue
  src/components/Properties/PropertySelect.vue
  src/components/Settings/SettingsAddressbook.vue
  src/components/Settings/SettingsImportContacts.vue
  src/components/Settings/SettingsSortContacts.vue
  src/main.js
  webpack.common.js
Labels: 3. to review, configuration, design, enhancement

#706 Sharing design and cdav request
  css/Settings/SettingsAddressbook.scss
  css/Settings/SettingsAddressbookSharee.scss
  css/Settings/SettingsAddressbookShares.scss
  package-lock.json
  package.json
  src/components/ContactDetails.vue
  src/components/ContactDetails/ContactDetailsAddNewProp.vue
  src/components/ContactDetails/ContactDetailsProperty.vue
  src/components/Properties/PropertyTitle.vue
  src/components/Settings/SettingsAddressbook.vue
  src/components/Settings/SettingsAddressbookShare.vue
  src/components/Settings/SettingsAddressbookSharee.vue
  src/main.js
  src/store/addressbooks.js
  src/views/Contacts.vue
  webpack.common.js
Labels: 3. to review, high

#716 Mixins
  css/ContactDetails.scss
  css/Properties/Properties.scss
  css/Settings/SettingsAddressbook.scss
  css/icons.scss
  img/address-book.svg
  img/eye.svg
  package-lock.json
  package.json
  src/components/ContactDetails.vue
  src/components/ContactDetails/ContactDetailsAddNewProp.vue
  src/components/ContactDetails/ContactDetailsProperty.vue
  src/components/Properties/PropertyDateTime.vue
  src/components/Properties/PropertyGroups.vue
  src/components/Properties/PropertyMultipleText.vue
  src/components/Properties/PropertySelect.vue
  src/components/Properties/PropertyText.vue
  src/components/Settings/SettingsAddressbookShare.vue
  src/main.js
  src/mixins/PropertyMixin.js
  src/router/index.js
  src/services/api.js
  webpack.common.js
Labels: 3. to review, design, enhancement, high

#717 Added external link support
  css/ContactDetailsAvatar.scss
  css/Properties/Properties.scss
  css/icons.scss
  img/phone.svg
  src/components/ContactDetails.vue
  src/components/Properties/PropertyText.vue
  src/models/rfcProps.js
  src/views/Contacts.vue
Labels: 3. to review, enhancement, high

#718 Select the fullname field if it is still set to New contact
  src/components/ContactDetails.vue
  src/views/Contacts.vue
Labels: 3. to review, enhancement

#719 actually display Copied label for 2 seconds
  src/components/Settings/SettingsAddressbook.vue
Labels: 4. to release, bug, design

#725 window.firstDay is zero based, vue2-timepickers first of of week is not
  src/components/Properties/PropertyDateTime.vue
Labels: 3. to review, bug

#726 Srinking optimisations and fixes
  css/ContactDetails.scss
  css/ContactDetailsAvatar.scss
  css/Properties/Properties.scss
  css/Properties/PropertyTitle.scss
  css/Settings/SettingsAddressbookShares.scss
  css/SettingsSection.scss
  src/components/ContactDetails/ContactDetailsAvatar.vue
  src/components/Properties/PropertySelect.vue
  src/components/Properties/PropertyTitle.vue
  src/components/Settings/SettingsImportContacts.vue
  src/store/contacts.js
Labels: 2. developing, design

#732 Properties fixes
  src/components/ContactDetails.vue
  src/components/ContactDetails/ContactDetailsAddNewProp.vue
  src/components/ContactDetails/ContactDetailsAvatar.vue
  src/components/ContactDetails/ContactDetailsProperty.vue
  src/components/ContactsList/ContactsListItem.vue
  src/components/Properties/PropertyGroups.vue
  src/components/Settings/SettingsAddressbookShare.vue
  src/models/contact.js
  src/models/rfcProps.js
  src/store/addressbooks.js
  src/store/contacts.js
  src/store/groups.js
  src/store/importState.js
Labels: 3. to review, bug, high

#734 use postfix option for routes to prevent having duplicate view controller methods
  appinfo/routes.php
  lib/Controller/PageController.php
Labels: 3. to review

#667 [issue-#39] It is now possible to download group of contacts.
  src/views/Contacts.vue
Labels: 3. to review, enhancement, medium

#741 Set max-version to 16 to make this app work on latest master
  appinfo/info.xml
Labels: 3. to review
