Repository nextcloud/contacts, pull requests merged in 2019-04, with the labels that each got.

#1035 Remove some properties if empty
  src/components/ContactsList/ContactsListItem.vue
  src/models/contact.js
Labels: 3. to review, compatibility, enhancement

#1042 Automatic repair of duplicate types
  src/services/checks/duplicateTypes.js
  src/services/checks/index.js
Labels: 3. to review, bug, enhancement

#1052 fixing displaced property title if tooltip icon shown
  css/Properties/Properties.scss
  css/Properties/PropertyTitle.scss
  src/components/Properties/PropertyTitle.vue
Labels: 3. to review, design

#1053 Contact Details: add some padding between header and properties
  css/ContactDetails.scss
Labels: 3. to review, design

#1055 Avoid qrcode getting cropped
  css/ContactDetails.scss
  src/components/ContactDetails.vue
Labels: 4. to release, bug, design

#1056 add cloud to fieldOrder, so it can be grouped in the UI
  src/models/rfcProps.js
Labels: 3. to review, enhancement

#1050 Use localcontact as default changes on properties
  src/components/ContactDetails.vue
  src/components/ContactDetails/ContactDetailsProperty.vue
  src/mixins/PropertyMixin.js
Labels: 3. to review, bug

#1064 Fix/compatibility/edge
  .babelrc.js
  css/ContactsList.scss
  package-lock.json
  package.json
  templates/main.php
  webpack.common.js
Labels: 3. to review, bug, compatibility, enhancement

#1074 Fix alignment and remove addressbook selector if only one
  css/Properties/Properties.scss
  src/components/ContactDetails.vue
  src/components/Properties/PropertyMultipleText.vue
Labels: 3. to review, bug, enhancement
