Repository nextcloud/contacts, pull requests merged in 2019-08, with the labels that each got.

#1229 Fix 111 high, 3 critical vulnerabilities in dependencies
  package-lock.json
Labels: 3. to review, bug, security

#1238 Bump nextcloud-vue to 0.12.2
  package-lock.json
Labels: 3. to review, enhancement

#1239 Support vcard 3 photo syntax
  src/components/ContactDetails/ContactDetailsAvatar.vue
  src/components/ContactsList/ContactsListItem.vue
  src/models/contact.js
Labels: 3. to review, bug
