Repository nextcloud/contacts, pull requests merged in 2019-01, with the labels that each got.

#816 Fix group vcard download
  package-lock.json
  package.json
  src/views/Contacts.vue
Labels: 3. to review, bug

#818 Make sure to properly set the month to the same start index than JS and moment
  src/components/Properties/PropertyDateTime.vue
Labels: 4. to release, bug, high

#817 Properly detect vdom local data change and update accordingly
  src/mixins/PropertyMixin.js
Labels: 3. to review, bug, high

#819 Make search case insensitive
  src/components/ContactsList/ContactsListItem.vue
Labels: 3. to review, enhancement

#820 Remove contact from group on contact deletion
  src/store/contacts.js
  src/store/groups.js
Labels: 3. to review, bug

#822 Addressbook deletion confirm
  src/components/Settings/SettingsAddressbook.vue
Labels: 3. to review, enhancement

#834 Federated cloud fix
  src/models/rfcProps.js
Labels: 4. to release, bug, regression

#825 fix gender field select
  src/components/ContactDetails.vue
  src/components/ContactDetails/ContactDetailsAddNewProp.vue
  src/components/Properties/PropertySelect.vue
  src/mixins/PropertyMixin.js
  src/models/rfcProps.js
Labels: 3. to review, bug, regression

#863 Update Datepicker script for nextcloud-vue 0.5.1
  package-lock.json
  package.json
  src/components/Properties/PropertyDateTime.vue
  webpack.dev.js
Labels: 3. to review

#864 Emit updatedcontact event on prop deletion
  src/components/ContactDetails/ContactDetailsProperty.vue
Labels: 3. to review

#867 Fix contactsmenu for 16
  lib/ContactsMenu/Providers/DetailsProvider.php
Labels: 3. to review, bug

#878 Use origin to generate the addressbook url
  src/components/Settings/SettingsAddressbook.vue
Labels: 3. to review, bug

#879 Queue contacts updates
  package-lock.json
  package.json
  src/components/ContactDetails.vue
Labels: 3. to review, bug, high

#880 Properly format displayName and fields validatation
  .eslintrc.js
  src/models/contact.js
  src/services/checks/index.js
  src/services/checks/missingFN.js
  src/services/parseVcf.js
  src/services/validate.js
  src/store/addressbooks.js
  src/store/contacts.js
  src/views/Contacts.vue
Labels: 3. to review

#898 Add property-defined actions and populate FN if unchanged or empty
  css/Properties/Properties.scss
  css/icons.scss
  img/up.svg
  package-lock.json
  src/components/ContactDetails.vue
  src/components/ContactDetails/ContactDetailsAddNewProp.vue
  src/components/ContactDetails/ContactDetailsAvatar.vue
  src/components/ContactDetails/ContactDetailsProperty.vue
  src/components/ContactsList/ContactsListItem.vue
  src/components/Properties/PropertyDateTime.vue
  src/components/Properties/PropertyMultipleText.vue
  src/components/Properties/PropertySelect.vue
  src/components/Properties/PropertyText.vue
  src/main.js
  src/mixins/PropertyMixin.js
  src/models/contact.js
  src/models/rfcProps.js
  src/services/checks/missingFN.js
  src/services/validate.js
  src/store/contacts.js
  src/views/Contacts.vue
Labels: 3. to review, bug, design, enhancement

#883 Url decode groups and users
  src/components/Settings/SettingsAddressbookShare.vue
Labels: 3. to review, bug
