Repository nextcloud/contacts, pull requests merged in 2019-10, with the labels that each got.

#1290 Better debug of the duplicate types check
  src/services/checks/duplicateTypes.js
Labels: 3. to review, enhancement

#1291 Implement our own initialStateService for 15
  lib/Controller/PageController.php
  templates/main.php
  tests/unit/Controller/PageControllerTest.php
Labels: 3. to review, bug, high

#1292 Provide our own initialstate
  src/models/rfcProps.js
  src/services/initialstate.js
Labels: 3. to review, bug, high

#1307 Make the work profile the default one when adding Contacts
  lib/Controller/PageController.php
  src/models/rfcProps.js
  templates/main.php
  tests/unit/Controller/PageControllerTest.php
Labels: 3. to review

#1314 Fix first day of datepicker
  src/components/Properties/PropertyDateTime.vue
Labels: 3. to review
