Repository nextcloud/contacts, pull requests merged in 2019-09, with the labels that each got.

#1249 Fix moment loading
  package-lock.json
  package.json
  src/components/Properties/PropertyDateTime.vue
Labels: 3. to review, bug

#1258 Allow master to work against nc 18
  appinfo/info.xml
Labels: 3. to review, bug, configuration

#1250 Added possibility to show and edit vCard Geo attributes
  src/components/ContactDetails/ContactDetailsAddNewProp.vue
  src/models/rfcProps.js
Labels: 3. to review, enhancement

#1276 Move to global eslint
  .babelrc.js
  .eslintrc.js
  package-lock.json
  package.json
  src/components/Actions/ActionCopyNtoFN.vue
  src/components/Actions/ActionToggleYear.vue
  src/components/ContactDetails.vue
  src/components/ContactDetails/ContactDetailsAddNewProp.vue
  src/components/ContactDetails/ContactDetailsAvatar.vue
  src/components/ContactDetails/ContactDetailsProperty.vue
  src/components/ContactsList/ContactsListItem.vue
  src/components/Properties/PropertyActions.vue
  src/components/Properties/PropertyDateTime.vue
  src/components/Properties/PropertyGroups.vue
  src/components/Properties/PropertyMultipleText.vue
  src/components/Properties/PropertySelect.vue
  src/components/Properties/PropertyText.vue
  src/components/Settings/SettingsAddressbook.vue
  src/components/Settings/SettingsAddressbookShare.vue
  src/components/Settings/SettingsAddressbookSharee.vue
  src/components/Settings/SettingsImportContacts.vue
  src/components/Settings/SettingsNewAddressbook.vue
  src/components/SettingsSection.vue
  src/main.js
  src/mixins/PropertyMixin.js
  src/router/index.js
  src/services/checks/badGenderType.js
  src/services/parseVcf.js
  src/services/validate.js
  src/store/addressbooks.js
  src/store/contacts.js
  src/views/Contacts.vue
  tests/.eslintrc.js
  tests/setup.js
  tests/unit/specs/Contacts.spec.js
  webpack.common.js
Labels: 3. to review, configuration, enhancement

#1264 Add TZ & LANG
  .gitignore
  .travis.yml
  Makefile
  README.md
  composer.json
  composer.lock
  css/icons.scss
  img/language.svg
  lib/Controller/PageController.php
  package-lock.json
  package.json
  src/components/Properties/PropertySelect.vue
  src/models/rfcProps.js
  src/models/zones.js
  tests/bootstrap.php
  tests/unit/Controller/PageControllerTest.php
Labels: 4. to release, enhancement

#982 Add push warning on fixed contact
  css/Properties/Properties.scss
  src/components/ContactDetails.vue
  src/components/Properties/PropertyText.vue
Labels: 2. developing, enhancement
