Repository nextcloud/contacts, pull requests merged in 2020-07, with the labels that each got.

#1690 Add php cs & stylelint
  .github/workflows/lint.yml
  .gitignore
  .php_cs.dist
  composer.json
  composer.lock
  lib/AppInfo/Application.php
  lib/ContactsMenu/Providers/DetailsProvider.php
  lib/Controller/PageController.php
  package-lock.json
  package.json
  templates/main.php
  tests/unit/ContactsMenu/Provider/DetailsProviderTest.php
  tests/unit/Controller/PageControllerTest.php
Labels: 3. to review, enhancement

#1691 Move routes to info.xml
  appinfo/app.php
  appinfo/info.xml
  lib/AppInfo/Application.php
Labels: 3. to review

#1645 Additional link to picture menu
  css/ContactDetailsAvatar.scss
  src/components/ContactDetails/ContactDetailsAvatar.vue
Labels: 4. to release, enhancement
