Repository nextcloud/contacts, pull requests merged in 2020-09, with the labels that each got.

#1755 Implement masonry
  css/ContactDetails.scss
  css/ContactsList.scss
  css/Properties/Properties.scss
  css/contacts.scss
  package-lock.json
  package.json
  src/components/ContactDetails.vue
  src/components/ContactDetails/ContactDetailsAddNewProp.vue
  src/components/ContactDetails/ContactDetailsProperty.vue
  src/components/ContactsList.vue
  src/components/Properties/PropertyDateTime.vue
  src/components/Properties/PropertyGroups.vue
  src/components/Properties/PropertyMultipleText.vue
  src/components/Properties/PropertySelect.vue
  src/components/Properties/PropertyText.vue
Labels: 3. to review, bug, design

#1770 Fix/virtual group
  lib/AppInfo/Application.php
  src/components/ContactDetails.vue
  src/components/ContactDetails/ContactDetailsAvatar.vue
  src/components/ContactsList.vue
  src/components/EntityPicker/EntityBubble.vue
  src/components/EntityPicker/EntityPicker.vue
  src/components/ProcessingScreen.vue
  src/components/Properties/PropertyGroups.vue
  src/components/Properties/PropertyText.vue
  src/components/Settings/SettingsAddressbook.vue
  src/components/Settings/SettingsAddressbookSharee.vue
  src/components/Settings/SettingsNewAddressbook.vue
  src/main.js
  src/store/addressbooks.js
  src/store/contacts.js
  src/views/Contacts.vue
Labels: 3. to review, bug

#1785 Fix files-actions script name
  src/files-action.js
  webpack.js
Labels: 3. to review

#1786 Fix avatar sanitize and cleanup code & css
  css/ContactDetailsAvatar.scss
  css/contacts.scss
  src/components/ContactDetails/ContactDetailsAvatar.vue
  src/models/contact.js
Labels: 3. to review, bug, high, security

#1788 Properly sort groups
  package-lock.json
  package.json
  src/views/Contacts.vue
Labels: 3. to review, bug, design, papercut

#1787 Fix default addressbook creation
  src/views/Contacts.vue
Labels: 3. to review, bug, regression

#1790 Add back the app details toggle
  css/contacts.scss
  src/views/Contacts.vue
Labels: 3. to review, bug, regression

#1792 Fix/various design
  css/Settings/SettingsAddressbook.scss
  css/contacts.scss
  package-lock.json
  package.json
  src/components/ContactDetails/ContactDetailsAvatar.vue
  src/components/EntityPicker/EntityBubble.vue
  src/components/EntityPicker/EntityPicker.vue
  src/components/ProcessingScreen.vue
  src/components/Settings/SettingsAddressbook.vue
  src/components/Settings/SettingsImportContacts.vue
  src/services/parseVcf.js
  src/store/addressbooks.js
  src/views/Contacts.vue
  src/views/Processing/AddToGroupView.vue
  src/views/Processing/ImportView.vue
Labels: 2. developing, bug, papercut

#1745 Update social avatars in chunks
  lib/Cron/SocialUpdate.php
  lib/Cron/SocialUpdateRegistration.php
  lib/Service/SocialApiService.php
  tests/unit/Service/SocialApiServiceTest.php
Labels: 3. to review, enhancement

#1805 Up max-version to 21 for server master compatibility
  appinfo/info.xml
Labels: 3. to review
