Repository nextcloud/contacts, pull requests merged in 2020-12, with the labels that each got.

#1960 Add favicons
  img/favicon-mask.svg
  img/favicon-touch.png
  img/favicon-touch.svg
  img/favicon.ico
  img/favicon.png
  img/favicon.svg
Labels: 3. to review, enhancement

#1972 Fix generating the redirect url
  lib/Controller/ContactsController.php
  tests/unit/Controller/ContactsControllerTest.php
Labels: 3. to review, bug

#1982 Fix masonry redraw
  src/components/ContactDetails.vue
Labels: 3. to review, bug, design, medium

#1996 Lint php8
  .github/workflows/lint.yml
Labels: 3. to review
