Repository nextcloud/contacts, pull requests merged in 2020-08, with the labels that each got.

#1732 Fix group filter trim
  src/models/contact.js
Labels: 3. to review, bug

#1722 allow for regular background updates of avatars from social networks
  .editorconfig
  .tx
  appinfo/info.xml
  appinfo/routes.php
  lib/Controller/PageController.php
  lib/Controller/SocialApiController.php
  lib/Cron/SocialUpdate.php
  lib/Cron/SocialUpdateRegistration.php
  lib/Service/SocialApiService.php
  lib/Settings/AdminSettings.php
  src/components/AdminSettings.vue
  src/components/SettingsSection.vue
  tests/unit/Controller/PageControllerTest.php
  tests/unit/Service/SocialApiServiceTest.php
Labels: 3. to review, enhancement

#1741 Support X-PHONETIC-FIRST-NAME and X-PHONETIC-LAST-NAME
  src/components/Properties/PropertyText.vue
  src/components/Settings/SettingsSortContacts.vue
  src/models/contact.js
  src/models/rfcProps.js
  src/store/addressbooks.js
Labels: 3. to review, discussion

#1759 add Zoom as instant messaging
  src/models/rfcProps.js
Labels: 3. to review, enhancement

#1761 Add Matrix to list of instant messaging networks
  src/models/rfcProps.js
Labels: 3. to review, enhancement
