Repository nextcloud/contacts, pull requests merged in 2020-04, with the labels that each got.

#1462 Add ability to clone contact
  css/ContactDetails.scss
  css/icons.scss
  img/clone.svg
  package-lock.json
  src/components/Actions/ActionCopyNtoFN.vue
  src/components/Actions/ActionToggleYear.vue
  src/components/ContactDetails.vue
  src/components/ContactDetails/ContactDetailsAddNewProp.vue
  src/components/ContactDetails/ContactDetailsAvatar.vue
  src/components/Properties/PropertyActions.vue
  src/components/Properties/PropertyDateTime.vue
  src/components/Properties/PropertyGroups.vue
  src/components/Properties/PropertyMultipleText.vue
  src/components/Properties/PropertySelect.vue
  src/components/Properties/PropertyText.vue
  src/components/Settings/SettingsAddressbook.vue
  src/components/Settings/SettingsAddressbookShare.vue
  src/components/Settings/SettingsImportContacts.vue
  src/components/Settings/SettingsSortContacts.vue
  src/main.js
  src/store/addressbooks.js
  src/views/Contacts.vue
Labels: 3. to review, enhancement

#1554 Update babel.config.js
  Makefile
  babel.config.js
  src/main.js
Labels: 3. to review

#1555 Correction of descriptions
  src/components/ContactDetails.vue
Labels: design

#1556 Correction of descriptions
  src/components/Settings/SettingsAddressbook.vue
Labels: design

#1557 Correction of descriptions
  src/components/Settings/SettingsNewAddressbook.vue
Labels: design

#1568 Allow to use any name for Group creation
  src/components/Properties/PropertyGroups.vue
Labels: 4. to release, bug

#1579 3.3.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#1582 Fix app init & initialstate
  appinfo/app.php
  appinfo/info.xml
  lib/AppInfo/Application.php
  lib/Controller/PageController.php
  src/models/rfcProps.js
  src/services/initialstate.js
  tests/unit/Controller/PageControllerTest.php
Labels: 3. to review, enhancement

#1592 Fix/template
  lib/Controller/PageController.php
  templates/main.php
Labels: 3. to review, enhancement

#1596 Show transparent contact photos on a lighter background
  css/ContactDetailsAvatar.scss
  src/components/ContactsList/ContactsListItem.vue
Labels: 3. to review, bug, design
