Repository nextcloud/contacts, pull requests merged in 2020-02, with the labels that each got.

#1438 Allow importing from files
  package-lock.json
  package.json
  src/components/ContactDetails/ContactDetailsAvatar.vue
  src/components/Properties/PropertyDateTime.vue
  src/components/Properties/PropertyMultipleText.vue
  src/components/Settings/SettingsImportContacts.vue
  src/components/SettingsSection.vue
  src/main.js
  src/models/rfcProps.js
  src/router/index.js
  src/services/cdav.js
Labels: 3. to review, enhancement, high

#1463 l10n: Changed spelling
  src/components/Settings/SettingsImportContacts.vue
Labels: 3. to review, bug

#1488 Fix first contact sync
  src/components/ContactDetails.vue
  src/store/contacts.js
Labels: 3. to review, bug, high
