Repository nextcloud/contacts, pull requests merged in 2020-05, with the labels that each got.

#1447 Remove header color bar as it is not related to the contact
  css/ContactDetails.scss
  src/components/ContactDetails.vue
Labels: 3. to review, design, enhancement

#1636 l10n: Changed spelling of URL
  src/models/rfcProps.js
Labels: 3. to review, enhancement

#1644 Fix Content-Wrapper CSS
  css/ContactDetails.scss
  css/contacts.scss
Labels: 3. to review, bug
