Repository nextcloud/contacts, pull requests merged in 2020-01, with the labels that each got.

#1394 Workaround for bug that prevented editing vCards with commas in the address
  src/mixins/PropertyMixin.js
  src/models/contact.js
  src/services/updateDesignSet.js
Labels: 3. to review, bug

#1393 Use correct syntax for vCard version when saving
  src/services/updateDesignSet.js
  src/store/contacts.js
Labels: 4. to release, bug, high

#1389 Move to @nextcloud/vue
  package-lock.json
  package.json
  src/components/Actions/ActionCopyNtoFN.vue
  src/components/Actions/ActionToggleYear.vue
  src/components/ContactDetails.vue
  src/components/ContactDetails/ContactDetailsAvatar.vue
  src/components/Properties/PropertyActions.vue
  src/components/Properties/PropertyDateTime.vue
  src/components/Settings/SettingsAddressbook.vue
  src/main.js
  src/views/Contacts.vue
Labels: 3. to review, dependencies

#1401 Only add sharee if not present already
  src/components/Settings/SettingsAddressbookShare.vue
  src/store/addressbooks.js
Labels: 3. to review, bug

#1413 remove delete buttons and other actions if contact is not readable
  css/Properties/Properties.scss
  src/components/Properties/PropertyDateTime.vue
  src/components/Properties/PropertyMultipleText.vue
  src/components/Properties/PropertySelect.vue
  src/components/Properties/PropertyText.vue
Labels: 3. to review, bug

#1412 short company field only if empty
  css/ContactDetails.scss
Labels: 3. to review, design

#1430 Remove delete action from list, fix #1368
  css/ContactsListItem.scss
  src/components/ContactsList/ContactsListItem.vue
Labels: 3. to review, design, enhancement

#1418 Disable form validation for text properties
  src/components/Properties/PropertyText.vue
Labels: 3. to review, bug

#1448 Fix sorting and wording of contact picture actions
  src/components/ContactDetails/ContactDetailsAvatar.vue
Labels: 3. to review, design, enhancement
