Repository nextcloud/contacts, pull requests merged in 2020-10, with the labels that each got.

#1819 Force redraw masonry on property resize
  src/components/ContactDetails.vue
  src/components/ContactDetails/ContactDetailsProperty.vue
  src/components/Properties/PropertyText.vue
Labels: 3. to review, bug

#1821 Fix social sync admin settings
  src/admin-settings.js
  templates/settings/admin.php
  webpack.js
Labels: 3. to review, bug

#1828 Fix placeholder display
  src/components/Properties/PropertyText.vue
Labels: 3. to review, bug, regression

#1843 more robust social ids for social sync
  lib/Service/Social/FacebookProvider.php
  lib/Service/Social/InstagramProvider.php
  lib/Service/Social/MastodonProvider.php
  lib/Service/Social/TumblrProvider.php
Labels: 3. to review, compatibility

#1853 adding diaspora to the list for social sync
  css/icons.scss
  img/diaspora.svg
  img/license.txt
  lib/Service/Social/CompositeSocialProvider.php
  lib/Service/Social/DiasporaProvider.php
Labels: 3. to review, enhancement

#1846 Fix avatar display on read-only contacts and use global Avatar component
  package-lock.json
  package.json
  src/components/ContactDetails/ContactDetailsAvatar.vue
  src/components/ContactsList/ContactsListItem.vue
  src/models/contact.js
Labels: 3. to review, bug, design

#1869 add xing to social sync
  css/icons.scss
  img/license.txt
  img/xing.svg
  lib/Service/Social/CompositeSocialProvider.php
  lib/Service/Social/XingProvider.php
Labels: 3. to review, enhancement

#1871 add xing to list of social networks
  src/models/rfcProps.js
Labels: 3. to review, design, enhancement

#1884 Fix Avatar ratio display
  src/components/ContactDetails/ContactDetailsAvatar.vue
Labels: 3. to review, bug, design

#1893 l10n: Rebuild string text
  src/views/Contacts.vue
Labels: 3. to review, enhancement
