Repository nextcloud/contacts, pull requests merged in 2020-11, with the labels that each got.

#1909 Bump eslint to 7 and associated dependencies
  package-lock.json
  package.json
  src/components/ContactDetails.vue
  src/components/ContactDetails/ContactDetailsAvatar.vue
  src/components/ContactDetails/ContactDetailsProperty.vue
  src/components/ContactsList.vue
  src/components/EntityPicker/EntitySearchResult.vue
  src/components/SettingsSection.vue
  src/models/contact.js
  src/services/parseVcf.js
  src/views/Contacts.vue
Labels: 3. to review, dependencies

#1906 add support for downloading avatars from gravatar
  css/icons.scss
  img/gravatar.svg
  img/license.txt
  lib/Service/Social/CompositeSocialProvider.php
  lib/Service/Social/DiasporaProvider.php
  lib/Service/Social/FacebookProvider.php
  lib/Service/Social/GravatarProvider.php
  lib/Service/Social/ISocialProvider.php
  lib/Service/Social/InstagramProvider.php
  lib/Service/Social/MastodonProvider.php
  lib/Service/Social/TumblrProvider.php
  lib/Service/Social/TwitterProvider.php
  lib/Service/Social/XingProvider.php
  lib/Service/SocialApiService.php
  src/components/ContactDetails/ContactDetailsAvatar.vue
  tests/unit/Service/Social/DiasporaProviderTest.php
  tests/unit/Service/Social/FacebookProviderTest.php
  tests/unit/Service/Social/GravatarProviderTest.php
  tests/unit/Service/Social/InstagramProviderTest.php
  tests/unit/Service/Social/MastodonProviderTest.php
  tests/unit/Service/Social/TumblrProviderTest.php
  tests/unit/Service/Social/TwitterProviderTest.php
  tests/unit/Service/Social/XingProviderTest.php
  tests/unit/Service/SocialApiServiceTest.php
Labels: 3. to review, enhancement

#1918 vcard should only have 1 photo field when adding/removing photos
  lib/Service/SocialApiService.php
  src/components/ContactDetails/ContactDetailsAvatar.vue
  tests/unit/Service/SocialApiServiceTest.php
Labels: 3. to review, bug

#1883 Fix bulk contacts add to group
  src/views/Contacts.vue
Labels: 3. to review, bug

#1894 new facebook api prevents usage without authentication
  lib/Service/Social/CompositeSocialProvider.php
Labels: 3. to review, bug

#1936 Replace the deprecated OC.Util.relativeModifiedDate by nextcloud/moment
  package-lock.json
  package.json
  src/components/Properties/PropertyRev.vue
Labels: 4. to release, enhancement

#1938 Fix/dav plugins groups registration
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review, bug
