Repository nextcloud/contacts, pull requests merged in 2021-12, with the labels that each got.

#2561 Create lint-info-xml.yml
  .github/workflows/lint-info-xml.yml
  appinfo/info.xml
Labels: 3. to review, configuration

#2566 Fix magic numbers of Circles config
  src/models/constants.ts
Labels: 3. to review

#2567 Fix release automation
  .github/workflows/appstore-build-publish.yml
  Makefile
Labels: bug, 3. to review

#2573 Rename `master` references to `main`
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit.yml
  appinfo/info.xml
Labels: 3. to review

#2575 fix overlapping of contacts-list with app-navigation-toogle
  src/components/ContactsList.vue
Labels: enhancement, 3. to review, design

#2531 new contact event fix
  src/views/Contacts.vue
Labels: bug, 4. to release, feature: contacts, backport-request

#2586 Update installation and contributors info on readme
  README.md
Labels: 3. to review

#2587 Update info.xml authors with new maintainers and co-maintainers
  appinfo/info.xml
Labels: 3. to review

#2589 Fix dev setup errors
  Makefile
  README.md
Labels: bug, 3. to review

#2590 Remove all obsolete make targets
  Makefile
Labels: 3. to review
