Repository nextcloud/contacts, pull requests merged in 2021-06, with the labels that each got.

#2244 l10n: Correct spelling
  src/components/AppNavigation/Settings/SettingsAddressbook.vue
  src/components/EntityPicker/NewCircleIntro.vue
  src/mixins/CircleActionsMixin.js
  src/models/constants.ts
  src/store/circles.js
Labels: 3. to review, bug

#2249 Properly check for circles version
  .eslintrc.js
  lib/Controller/PageController.php
  package-lock.json
  package.json
  src/main.js
  src/services/logger.js
  src/views/Contacts.vue
  tests/unit/Controller/PageControllerTest.php
Labels: 3. to review, bug

#2247 Fix personal circle wording and hide feature
  src/components/EntityPicker/NewCircleIntro.vue
Labels: 4. to release, bug

#2251 Disable new circle buttons on loading
  src/components/EntityPicker/NewCircleIntro.vue
Labels: 3. to review, bug, feature: circles

#2252 Fix add members NavigationDuplicated error
  src/mixins/CircleActionsMixin.js
Labels: 3. to review, bug, feature: circles

#2253 Fix init circle loading and logger debug
  src/components/AppContent/CircleContent.vue
  src/components/AppNavigation/RootNavigation.vue
  src/components/CircleDetails/CircleConfigs.vue
  src/components/ContactDetails.vue
  src/components/MemberList.vue
  src/components/MembersList/MembersListItem.vue
  src/mixins/CircleActionsMixin.js
  src/models/member.d.ts
  src/models/member.ts
  src/store/circles.js
  src/views/Contacts.vue
Labels: 3. to review, bug, feature: circles

#2254 Admins can also promote others as admin
  src/components/MemberList.vue
  src/components/MembersList/MembersListItem.vue
Labels: 3. to review, bug, feature: circles

#2250 Show explanatory description on empty circles list
  src/components/AppNavigation/RootNavigation.vue
  src/components/EntityPicker/NewCircleIntro.vue
  src/models/constants.d.ts
  src/models/constants.ts
Labels: 3. to review, enhancement, feature: circles

#2255 Close add some menu entries after click
  src/components/AppNavigation/CircleNavigationItem.vue
  src/components/AppNavigation/GroupNavigationItem.vue
Labels: 3. to review, bug, feature: circles, feature: contacts

#2264 Fix circles version comparison if circles is not installed
  lib/Controller/PageController.php
Labels: 3. to review, bug, feature: circles

#2281 Bump deps and use npm7
  .github/workflows/lint.yml
  .github/workflows/node.yml
  package-lock.json
  package.json
  stylelint.config.js
Labels: 3. to review, enhancement, feature: dependencies

#2286 Fix chain condition of responses
  src/components/ContactDetails.vue
  src/components/ContactDetails/ContactDetailsAvatar.vue
  src/components/MembersList/MembersListItem.vue
  src/store/contacts.js
Labels: 3. to review, bug

#2287 Fix Circle class name comparison
  src/models/member.ts
Labels: 3. to review, bug

#2246 Comply to new resizeable list feature
  css/contacts.scss
  package-lock.json
  src/components/AppContent/AppDetailsToggle.vue
  src/components/AppContent/CircleContent.vue
  src/components/AppContent/ContactsContent.vue
  src/components/ContactDetails.vue
  src/views/Contacts.vue
Labels: 4. to release, enhancement

#2295 Support population count
  src/components/AppNavigation/CircleNavigationItem.vue
  src/models/circle.d.ts
  src/models/circle.ts
Labels: 1. to develop, enhancement

#2298 Support contacts member type
  src/components/MemberList.vue
  src/models/constants.ts
Labels: 3. to review, bug, feature: circles
