Repository nextcloud/contacts, pull requests merged in 2021-02, with the labels that each got.

#2061 Bump composer deps
  .github/workflows/phpunit.yml
  composer.json
  composer.lock
  phpunit.integration.xml
Labels: 3. to review, dependencies

#2064 Fix custom labels not being displayed
  src/components/ContactDetails.vue
Labels: 3. to review, bug, high

#2076 Alphabetically order groups in contact details (#2051)
  src/components/Properties/PropertyGroups.vue
Labels: 3. to review, bug

#2083 instagram profile sync with agent
  lib/Service/Social/InstagramProvider.php
  tests/unit/Service/Social/InstagramProviderTest.php
Labels: 3. to review

#2081 adapted twitter uri
  lib/Service/Social/TwitterProvider.php
  tests/unit/Service/Social/TwitterProviderTest.php
Labels: 3. to review

#2085 use all email addresses for gravatar search
  lib/Service/SocialApiService.php
Labels: 3. to review

#2086 Fix contact deletion from addressbook
  src/store/addressbooks.js
Labels: 3. to review, bug
