Repository nextcloud/contacts, pull requests merged in 2021-08, with the labels that each got.

#2383 allow to scroll the app-content-details
  css/contacts.scss
Labels: enhancement, 3. to review, design

#2400 Use sharing constants from a package, not another app
  package-lock.json
  package.json
  src/models/constants.d.ts
  src/models/constants.ts
Labels: 3. to review

#2417 Fixed search / filter at add contacts dialog is case sensitive issue #1939
  src/components/EntityPicker/EntityPicker.vue
Labels: bug, 4. to release

#2410 fix some settings styling
  css/SettingsSection.scss
  src/components/AppNavigation/Settings/SettingsAddressbook.vue
Labels: enhancement, 3. to review, design
