Repository nextcloud/contacts, pull requests merged in 2022-05, with the labels that each got.

#2720 Fix social api service null url
  lib/ContactsMenu/Providers/DetailsProvider.php
  lib/Service/SocialApiService.php
  tests/unit/Service/SocialApiServiceTest.php
Labels: bug, 3. to review, feature: contacts

#2658 Fix content details container height
  src/components/ContactDetails.vue
Labels: bug, 3. to review, design

#2663 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: 4. to release, dependencies

#2745 Resize maximum dimensions for pictures coming from SocialApiService
  lib/Service/ImageResizer.php
  lib/Service/SocialApiService.php
  tests/unit/Service/ImageResizerTest.php
  tests/unit/Service/SocialApiServiceTest.php
Labels: 3. to review

#2727 Fix screenshot link in appstore
  appinfo/info.xml
Labels: backport-request

#2744 When delete last member from group, it is not update data on server
  src/components/Properties/PropertyGroups.vue
Labels: bug, 4. to release, backport-request

#2732 Allow to input the Date by hand
  src/components/Properties/PropertyDateTime.vue
Labels: enhancement, 3. to review
