Repository nextcloud/contacts, pull requests merged in 2022-07, with the labels that each got.

#2808 Migrate icons to material design icons
  src/components/ContactDetails.vue
  src/components/Icons/IconAddressBook.vue
  src/components/Properties/PropertyActions.vue
  src/components/Properties/PropertyTitle.vue
  src/components/Properties/PropertyTitleIcon.vue
Labels: 4. to release

#2711 Add search feature on the list
  src/components/ContactsList.vue
Labels: enhancement, 4. to release

#2837 Fix entity picker modal size
  src/components/EntityPicker/EntityPicker.vue
Labels: bug, 3. to review, design, regression, backport-request

#2835 Fix qr modal size
  src/components/ContactDetails.vue
Labels: bug, 3. to review, design, regression, backport-request

#2807 Migrate settings menu icons of contacts to material design icons
  css/SettingsSection.scss
  src/components/AppNavigation/Settings/SettingsAddressbook.vue
  src/components/AppNavigation/Settings/SettingsNewAddressbook.vue
  src/components/AppNavigation/Settings/SettingsSortContacts.vue
  src/components/AppNavigation/SettingsSection.vue
  src/components/CircleDetails/CirclePasswordSettings.vue
Labels: bug, 4. to release, design, regression, backport-request

#2845 Include scss sheets in js bundle
  css/Properties/Properties.scss
  css/SettingsSection.scss
  css/contacts.scss
  css/icons.scss
  lib/Controller/PageController.php
  src/main.js
Labels: 3. to review, technical debt

#2844 Fix copy to full name and omit year actions
  src/components/Actions/ActionCopyNtoFN.vue
  src/components/Properties/PropertyActions.vue
  src/components/Properties/PropertyDateTime.vue
Labels: bug, 3. to review, regression, backport-request

#2765 Encode group names for x-property-replace header
  lib/Dav/PatchPlugin.php
  src/services/appendContactToGroup.js
Labels: bug, 3. to review, backport-request

#2817 Fix styling regression on contacts
  src/components/ContactDetails.vue
  src/components/ContactDetails/ContactDetailsAddNewProp.vue
  src/components/Properties/PropertyGroups.vue
  src/components/Properties/PropertyMultipleText.vue
  src/components/Properties/PropertySelect.vue
  src/components/Properties/PropertyText.vue
  src/components/Properties/PropertyTitle.vue
Labels: bug, 4. to release, design, regression, backport-request

#2857 Release v4.2.0
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review
