Repository nextcloud/contacts, pull requests merged in 2022-03, with the labels that each got.

#2659 Do not run server master tests on PHP7.3
  .github/workflows/phpunit.yml
Labels: 3. to review

#2665 Updating node.yml workflow from template
  .github/workflows/node.yml
Labels: dependencies

#2632 Force disabling single-quote list for type parameter
  .github/workflows/node-test.yml
  jest.config.js
  package-lock.json
  package.json
  src/components/AppNavigation/GroupNavigationItem.vue
  src/components/ContactsList.vue
  src/models/contact.js
  src/models/rfcProps.js
  src/services/updateDesignSet.js
  src/store/contacts.js
  tests/javascript/models/contact.test.js
  tests/setup.js
Labels: bug, 3. to review, technical debt

#2673 Improve addressbook enabled wording
  src/components/AppNavigation/Settings/SettingsAddressbook.vue
Labels: enhancement, 3. to review, papercut

#2674 Change fill to white to match other icons.
  img/contacts.svg
Labels: bug, 3. to review, design

#2683 Add PHP8.1 support
  .github/workflows/lint-php.yml
  .github/workflows/phpunit.yml
  appinfo/info.xml
  composer.json
  composer.lock
Labels: enhancement, 3. to review

#2686 Fix form id duplication
  .github/ISSUE_TEMPLATE/bug_report_circles.yml
  .github/ISSUE_TEMPLATE/bug_report_contacts.yml
  .github/ISSUE_TEMPLATE/feature_request_form.yml
Labels: bug, 3. to review
