Repository nextcloud/contacts, pull requests merged in 2022-12, with the labels that each got.

#3118 Fix sass division deprecation warnings
  src/components/EntityPicker/EntityPicker.vue
  src/components/EntityPicker/EntitySearchResult.vue
  src/components/EntityPicker/NewCircleIntro.vue
Labels: 3. to review, technical debt

#3117 Revert "Bump vue and vue-template-compiler"
  package-lock.json
  package.json
Labels: bug, 4. to release, regression, technical debt

#3124 fix docs link
  appinfo/info.xml
Labels: bug, 4. to release

#3125 Remove outdated IRC reference
  .github/config.yml
  README.md
Labels: 3. to review

#3133 Rephraze "There is no member in this circle"
  src/components/MemberList.vue
Labels: bug, 3. to review, feature: circles

#3049 Updating lint-php.yml workflow from template
  .github/workflows/lint-php.yml
Labels: 4. to release, dependencies

#2883 Update npm and node engines versions
  package-lock.json
  package.json
Labels: 4. to release, dependencies

#3137 chore(deps): Configure Dependabot to send semantic bump commits
  .github/dependabot.yml
Labels: 3. to review
