Repository nextcloud/contacts, pull requests merged in 2022-09, with the labels that each got.

#2915 Remove min-width to avoid alignment issue
  src/components/ProcessingScreen.vue
Labels: bug, 4. to release, design

#2928 Downgrade to Vue 2.6
  package-lock.json
  package.json
Labels: bug, 4. to release, regression, technical debt

#2917 Bump @nextcloud/vue v7.0.0-beta.3
  package-lock.json
  package.json
  src/components/Actions/ActionCopyNtoFN.vue
  src/components/Actions/ActionToggleYear.vue
  src/components/AppContent/CircleContent.vue
  src/components/AppContent/ContactsContent.vue
  src/components/AppNavigation/CircleNavigationItem.vue
  src/components/AppNavigation/GroupNavigationItem.vue
  src/components/AppNavigation/RootNavigation.vue
  src/components/AppNavigation/Settings/SettingsAddressbook.vue
  src/components/AppNavigation/Settings/SettingsAddressbookShare.vue
  src/components/AppNavigation/Settings/SettingsAddressbookSharee.vue
  src/components/AppNavigation/Settings/SettingsImportContacts.vue
  src/components/AppNavigation/Settings/SettingsNewAddressbook.vue
  src/components/AppNavigation/Settings/SettingsSortContacts.vue
  src/components/AppNavigation/SettingsSection.vue
  src/components/CircleDetails.vue
  src/components/CircleDetails/CircleConfigs.vue
  src/components/CircleDetails/CirclePasswordSettings.vue
  src/components/ContactDetails.vue
  src/components/ContactDetails/ContactDetailsAddNewProp.vue
  src/components/ContactDetails/ContactDetailsAvatar.vue
  src/components/ContactsList.vue
  src/components/ContactsList/ContactsListItem.vue
  src/components/DetailsHeader.vue
  src/components/EntityPicker/ContactsPicker.vue
  src/components/EntityPicker/EntityBubble.vue
  src/components/EntityPicker/EntityPicker.vue
  src/components/EntityPicker/EntitySearchResult.vue
  src/components/EntityPicker/NewCircleIntro.vue
  src/components/MemberList.vue
  src/components/MembersList/MembersListItem.vue
  src/components/ProcessingScreen.vue
  src/components/Properties/PropertyActions.vue
  src/components/Properties/PropertyDateTime.vue
  src/components/Properties/PropertyGroups.vue
  src/components/Properties/PropertyMultipleText.vue
  src/components/Properties/PropertySelect.vue
  src/components/Properties/PropertyText.vue
  src/views/Contacts.vue
Labels: 4. to release

#2931 Main will be v5.0.0
  appinfo/info.xml
Labels: 3. to review

#2954 Add organization charts
  package-lock.json
  package.json
  src/components/AppContent/ChartContent.vue
  src/components/AppContent/ContactsContent.vue
  src/components/AppNavigation/RootNavigation.vue
  src/components/ChartTemplate.vue
  src/components/ContactDetails.vue
  src/components/ContactDetails/ContactDetailsAddNewProp.vue
  src/components/ContactDetails/ContactDetailsProperty.vue
  src/components/OrgChart.vue
  src/components/Properties/PropertySelect.vue
  src/mixins/OrgChartsMixin.js
  src/models/constants.d.ts
  src/models/constants.ts
  src/models/contact.js
  src/models/rfcProps.js
  src/router/index.js
  src/utils/chartUtils.js
  src/views/Contacts.vue
Labels: enhancement, 3. to review

#2973 Sort org charts
  src/components/OrgChart.vue
Labels: bug, 3. to review, design

#2981 Ensure padding for entity picker input text area
  src/components/EntityPicker/EntityPicker.vue
Labels: bug, 3. to review, design

#2962 Save UID and display name for managers of the org chart
  src/components/AppContent/ChartContent.vue
  src/components/ContactDetails/ContactDetailsProperty.vue
  src/models/contact.js
  src/utils/chartUtils.js
Labels: 4. to release

#2647 Fix missing strict types for the social service
  lib/Service/SocialApiService.php
Labels: 4. to release, technical debt

#2620 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#2984 [stable5.0] Fix CI matrix
  .github/workflows/phpunit.yml
Labels: 3. to review

#2946 Properly decode escaped principal urls
  src/components/AppNavigation/Settings/SettingsAddressbookShare.vue
  src/utils/url.js
  tests/javascript/utils/url.test.js
Labels: bug, 3. to review, backport-request

#2989 Fix styling of org charts more button
  src/components/OrgChart.vue
Labels: bug, 3. to review

#2990 Ask Dependabot for security updates on stable4.2
  .github/dependabot.yml
Labels: 3. to review

#2997 Fix address book picker
  src/components/ContactDetails.vue
  src/components/Properties/PropertySelect.vue
Labels: bug, 3. to review, backport-request

#3000 Refactor manger property select logic
  src/components/ContactDetails.vue
  src/components/ContactDetails/ContactDetailsProperty.vue
  src/components/Properties/PropertySelect.vue
  src/mixins/OrgChartsMixin.js
  src/models/rfcProps.js
  src/utils/chartUtils.js
Labels: bug, 3. to review, regression, backport-request

#3002 Fix scrolling on mobile
  src/components/ContactDetails.vue
Labels: bug, 3. to review, regression, backport-request
