Repository nextcloud/contacts, pull requests merged in 2022-01, with the labels that each got.

#2594 Remove OC_Util::isIe()
  templates/main.php
Labels: bug, 3. to review, backport-request

#2597 Improve support for development on windows
  package.json
  webpack.config.js
Labels: enhancement, 3. to review

#2622 Fix usage of IgnorePlugin
  webpack.config.js
Labels: 3. to review, technical debt

#2579 Fix adding members when allowed for members
  src/models/circle.d.ts
  src/models/circle.ts
Labels: 4. to release, backport-request
