Repository nextcloud/contacts, pull requests merged in 2022-06, with the labels that each got.

#2762 Add PHP8.2 linting
  .github/workflows/lint-php.yml
Labels: 3. to review

#2739 Stop overwritting the name of the new contact by the company text
  src/services/checks/missingFN.js
Labels: bug, 4. to release

#2785 Avoid running social update background job on deleted/disabled users
  lib/Cron/SocialUpdate.php
  lib/Cron/SocialUpdateRegistration.php
Labels: bug, 3. to review

#2798 Fix mixing jest v27 and v28
  package-lock.json
  package.json
Labels: 4. to release, technical debt

#2766 Implement share password settings
  src/components/CircleDetails.vue
  src/components/CircleDetails/CirclePasswordSettings.vue
  src/services/circles.d.ts
  src/services/circles.ts
  src/store/circles.js
Labels: enhancement, 4. to release, feature: circles

#2801 Migrate left sidebar to material design icons
  src/components/AppNavigation/CircleNavigationItem.vue
  src/components/AppNavigation/GroupNavigationItem.vue
  src/components/AppNavigation/RootNavigation.vue
  src/components/Icons/IconRecentlyContacted.vue
Labels: 3. to review

#2799 Migrate EmptyContent contacts icons to material design
  src/components/AppContent/ContactsContent.vue
  src/components/ContactDetails.vue
  src/components/MemberList.vue
Labels: 3. to review

#2805 l10n: Changed casing
  src/components/CircleDetails/CirclePasswordSettings.vue
Labels: 4. to release
