Repository nextcloud/contacts, pull requests merged in 2022-02, with the labels that each got.

#2077 Allow sending emails to contact group (#1848)
  src/components/AppNavigation/GroupNavigationItem.vue
Labels: enhancement, 2. developing

#2596 Change formatter prop from :format to :formatter
  src/components/Properties/PropertyDateTime.vue
Labels: enhancement, 4. to release

#2637 Migrate template to form
  .github/ISSUE_TEMPLATE/bug_report_circles.md
  .github/ISSUE_TEMPLATE/bug_report_circles.yml
  .github/ISSUE_TEMPLATE/bug_report_contacts.md
  .github/ISSUE_TEMPLATE/bug_report_contacts.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request_form.yml
Labels: 2. developing

#2613 Updating lint-php.yml workflow from template
  .github/workflows/lint-php.yml
Labels: dependencies

#2626 Updating fixup.yml workflow from template
  .github/workflows/fixup.yml
Labels: dependencies

#2645 Mark background jobs as time sensitive/insensitive
  lib/Cron/SocialUpdateRegistration.php
Labels: enhancement, 3. to review
