Repository nextcloud/contacts, pull requests merged in 2023-06, with the labels that each got.

#3422 Hide empty properties in view mode
  src/components/ContactDetails.vue
  src/components/Properties/PropertyMultipleText.vue
  src/components/Properties/PropertySelect.vue
  src/components/Properties/PropertyText.vue
Labels: 3. to review

#3443 Bump stable5.3 to 5.3.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#3439 Contacts' import modal improvement
  src/components/AppNavigation/Settings/SettingsImportContacts.vue
Labels: bug, 3. to review, feature: contacts

#3453 Show single-value dropDowns as text in view mode
  src/components/Properties/PropertyGroups.vue
  src/components/Properties/PropertySelect.vue
Labels: enhancement, 3. to review

#3444 fix: Allow dynamic autoloading for classes added during upgrade
  composer.json
Labels: bug, 3. to review, regression, backport-request

#3455 Release 5.3.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#3399 enh(addressbooks): add show/hide option for system and shared addressbooks
  src/components/AppNavigation/Settings/SettingsAddressbook.vue
  src/store/addressbooks.js
  src/views/Contacts.vue
Labels: bug, enhancement

#3468 Release 5.3.2
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#3452 Fix handling group update
  src/components/ContactDetails.vue
  src/components/Properties/PropertyGroups.vue
  src/store/groups.js
Labels: bug, 3. to review, regression, feature: contacts
