Repository nextcloud/contacts, pull requests merged in 2023-03, with the labels that each got.

#3243 remove quotes on import
  src/store/addressbooks.js
Labels: bug, 3. to review, compatibility, feature: contacts

#3282 Fix typo in ContactDetails.vue
  src/components/ContactDetails.vue
Labels: bug, 4. to release

#3169 Add Threema as another option for Instant Messenger
  src/models/rfcProps.js
Labels: enhancement, 4. to release

#3280 add button to send emails to group as bcc
  src/components/AppNavigation/GroupNavigationItem.vue
Labels: enhancement, 4. to release
