Repository nextcloud/contacts, pull requests merged in 2023-10, with the labels that each got.

#3642 Add support for php8.3
  .github/workflows/lint-php.yml
  .github/workflows/phpunit.yml
  appinfo/info.xml
  composer.json
  composer.lock
Labels: 3. to review

#3653 fix: improve matching for tel type parameter
  src/components/ContactDetails/ContactDetailsProperty.vue
Labels: bug, 4. to release

#3661 fix: bundle moment.js locale data
  webpack.config.js
Labels: bug, 4. to release, backport-request

#3656 refactor: move type matching to own function
  src/components/ContactDetails/ContactDetailsProperty.vue
  src/utils/matchTypes.d.ts
  src/utils/matchTypes.ts
  tests/javascript/utils/matchTypes.test.ts
Labels: enhancement, 3. to review

#3635 Update selectInput to select on "Name"
  src/components/ContactDetails.vue
Labels: bug, 3. to review, backport-request

#3650 fix v-model of address book select control
  src/components/AppNavigation/Settings/SettingsImportContacts.vue
Labels: bug, 3. to review, feature: contacts, backport-request

#3663 chore(deps): bump @nextcloud/moment to 1.2.2
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#3664 [stable5.4] chore(deps): bump @nextcloud/moment to 1.2.2
  package-lock.json
  package.json
Labels: 3. to review, dependencies
