Repository nextcloud/contacts, pull requests merged in 2023-05, with the labels that each got.

#3359 Fix icon opacity for property actions
  src/components/Properties/PropertyActions.vue
  src/components/Properties/PropertyTitleIcon.vue
Labels: 3. to review

#3360 feat(contacts): implement final design enhancements from mockups
  css/Properties/Properties.scss
  src/components/ContactDetails.vue
  src/components/DetailsHeader.vue
  src/components/Properties/PropertyTitle.vue
Labels: 4. to release, design, feature: contacts

#3367 fix(contacts): remove obsolete warning and fix header alignment
  src/components/ContactDetails.vue
  src/components/DetailsHeader.vue
Labels: bug, 4. to release, design, feature: contacts

#3366 fix(contacts): display the new avatar on change
  src/components/AppContent/ContactsContent.vue
  src/components/ContactDetails.vue
  src/components/ContactDetails/ContactDetailsAvatar.vue
  src/components/ContactDetails/ContactDetailsProperty.vue
  src/components/ContactsList.vue
  src/components/ContactsList/ContactsListItem.vue
  src/components/Properties/PropertyGroups.vue
Labels: bug, 3. to review, feature: contacts

#3376 Use the color-primary-element* variables
  src/components/ChartTemplate.vue
  src/components/EntityPicker/EntitySearchResult.vue
  src/components/OrgChart.vue
Labels: bug, 3. to review, design

#3377 Fix:Form is transitioned into view mode when saving fails
  src/components/ContactDetails.vue
  src/store/contacts.js
Labels: bug, 4. to release, feature: contacts, skill:frontend

#3374 Replace NcMultiselect with NcSelect
  src/components/AppNavigation/Settings/SettingsAddressbookShare.vue
  src/components/AppNavigation/Settings/SettingsImportContacts.vue
  src/components/AppNavigation/Settings/SettingsSortContacts.vue
  src/components/ContactDetails.vue
  src/components/Properties/PropertyDateTime.vue
  src/components/Properties/PropertyGroups.vue
  src/components/Properties/PropertyMultipleText.vue
  src/components/Properties/PropertySelect.vue
  src/components/Properties/PropertyText.vue
Labels: enhancement, 3. to review, technical debt

#3382 Add contact and group counters to address books
  src/components/AppNavigation/Settings/SettingsAddressbook.vue
Labels: enhancement, 3. to review, skill:frontend

#3392 Add Nextcloud 28 support
  appinfo/info.xml
Labels: 3. to review

#3394 Fix:Add missing loading Icon
  src/components/AppNavigation/Settings/SettingsNewAddressbook.vue
Labels: 3. to review, skill:frontend

#2419 Fix Don't show groups in share placeholder if group sharing is disabled #2242
  lib/Controller/PageController.php
  src/components/AppNavigation/Settings/SettingsAddressbookShare.vue
  src/services/isGroupSharingEnabled.js
Labels: 4. to release

#3400 chore(CI): Adjust testing matrix for Nextcloud 27 on stable5.3
  .github/workflows/phpunit.yml
Labels: 3. to review

#3407 Bump stable5.3 to 5.3.0-rc.2
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#3413 feat(contacts): Show address book description if provided
  src/components/AppNavigation/Settings/SettingsAddressbook.vue
Labels: enhancement, 3. to review, feature: contacts

#3423 Hide contact groups if its empty
  src/components/Properties/PropertyGroups.vue
Labels: 3. to review

#3425 Fix: Search for new sharees of an addressbook
  src/components/AppNavigation/Settings/SettingsAddressbookShare.vue
Labels: 3. to review, regression, skill:frontend
