Repository nextcloud/contacts, pull requests merged in 2023-08, with the labels that each got.

#3532 Improve quick actions design
  src/components/ContactDetails.vue
Labels: 3. to review

#3534 release v5.4.0-alpha.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#3552 release v5.4.0-beta1
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#3565 ActionLink should be shown as a secondary button on quick actions
  src/components/ContactDetails.vue
Labels: 3. to review

#3567 Made contact image action menu only display in edit mode
  src/components/ContactDetails/ContactDetailsAvatar.vue
Labels: enhancement, 4. to release, design

#3568 Proper positioning of "Import contacts" and "New contact" buttons
  src/views/Contacts.vue
Labels: bug, 3. to review, design

#3569 release v5.4.0-beta2
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#3472 chore: update node engines to next LTS
  package.json
Labels: 3. to review, dependencies, automated

#3436 May fix some translations calls
  src/models/constants.ts
Labels: bug, 3. to review, feature: circles

#3579 Made Circles info always display
  src/components/AppNavigation/RootNavigation.vue
Labels: enhancement, 3. to review, design, feature: circles

#3581 Moved QR code close button away from QR code image
  src/components/ContactDetails.vue
Labels: bug, 3. to review, feature: contacts

#3576 Fix eslint config
  .eslintrc.js
  package-lock.json
  package.json
  src/components/AppNavigation/Settings/SettingsAddressbook.vue
  src/components/AppNavigation/Settings/SettingsImportContacts.vue
  src/components/CircleDetails.vue
  src/components/ContactDetails.vue
  src/components/ContactDetails/ContactDetailsAvatar.vue
  src/components/EntityPicker/ContactsPicker.vue
  src/components/OrgChart.vue
  src/components/Properties/PropertyDateTime.vue
  src/mixins/CircleActionsMixin.js
  src/mixins/OrgChartsMixin.js
  src/models/circle.d.ts
  src/models/circle.ts
  src/models/constants.d.ts
  src/models/constants.ts
  src/models/contact.js
  src/models/member.d.ts
  src/models/member.ts
  src/services/circles.d.ts
  src/services/circles.ts
  src/services/collaborationAutocompletion.js
  src/store/addressbooks.js
  src/utils/chartUtils.js
  src/views/Contacts.vue
  src/views/Processing/AddToGroupView.vue
  src/views/Processing/ImportView.vue
Labels: 3. to review, technical debt

#3591 release v5.4.0-beta3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#3594 Release v5.4.0-rc1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review
