Repository nextcloud/contacts, pull requests merged in 2023-11, with the labels that each got.

#3669 Import file FileAction 28 compatibility
  lib/Listener/LoadContactsFilesActions.php
  package-lock.json
  package.json
  src/files-action.js
  webpack.config.js
Labels: 4. to release, technical debt

#3685 Revert "chore(deps-dev): bump @babel/preset-env from 7.22.20 to 7.23.2"
  package-lock.json
  package.json
Labels: bug, 4. to release, dependencies

#3687 chore(release): v5.5.0-beta2
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#3689 chore(release): v5.5.0-beta3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 4. to release

#3690 Fix the permission check on files-actions
  lib/Listener/LoadContactsFilesActions.php
  src/files-action.js
Labels: 3. to review

#3695 Upgrade to Nextcloud vue 8.0.0
  package-lock.json
  package.json
  src/components/AppContent/CircleContent.vue
  src/components/AppContent/ContactsContent.vue
  src/components/AppNavigation/CircleNavigationItem.vue
  src/components/AppNavigation/ContactsSettings.vue
  src/components/AppNavigation/GroupNavigationItem.vue
  src/components/AppNavigation/RootNavigation.vue
  src/components/AppNavigation/Settings/SettingsAddressbook.vue
  src/components/AppNavigation/Settings/SettingsImportContacts.vue
  src/components/ContactDetails.vue
  src/components/ContactDetails/ContactDetailsAddNewProp.vue
  src/components/ContactsList.vue
  src/components/ContactsList/ContactsListItem.vue
  src/components/EntityPicker/EntityPicker.vue
  src/components/MemberList.vue
  src/components/MembersList/MembersListItem.vue
  src/components/OrgChart.vue
  src/components/ProcessingScreen.vue
  src/components/Properties/PropertyDateTime.vue
  webpack.config.js
Labels: enhancement, 3. to review

#3670 Add shared items and events for each contact
  src/components/ContactDetails.vue
Labels: enhancement, 3. to review, feature: contacts

#3697 chore(release): v5.5.0-beta4
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#3714 chore(release): v5.5.0-rc1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#3681 fix(socialavatars): Fix HTTP client usage
  lib/Service/Social/DiasporaProvider.php
  lib/Service/Social/FacebookProvider.php
  lib/Service/Social/InstagramProvider.php
  lib/Service/Social/MastodonProvider.php
  lib/Service/Social/TelegramProvider.php
  lib/Service/Social/XingProvider.php
  lib/Service/SocialApiService.php
  tests/unit/Service/Social/DiasporaProviderTest.php
  tests/unit/Service/Social/FacebookProviderTest.php
  tests/unit/Service/Social/InstagramProviderTest.php
  tests/unit/Service/Social/MastodonProviderTest.php
  tests/unit/Service/Social/TelegramProviderTest.php
  tests/unit/Service/Social/XingProviderTest.php
  tests/unit/Service/SocialApiServiceTest.php
Labels: bug, 3. to review, backport-request
