Repository nextcloud/contacts, pull requests merged in 2023-12, with the labels that each got.

#3737 Chore/release v5.5.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#3740 Fix rename types in propreties
  src/components/Properties/PropertyMultipleText.vue
  src/components/Properties/PropertyText.vue
  src/mixins/PropertyMixin.js
Labels: 3. to review, regression

#3688 chore: fix prod build after updating babel/preset-env
  src/views/Contacts.vue
Labels: 3. to review

#3751 Remove import contact button from chart view
  src/views/Contacts.vue
Labels: bug, 3. to review, skill:frontend

#3753 Fix: extra primary elements
  src/views/Contacts.vue
Labels: bug, 3. to review, design
