Repository nextcloud/contacts, pull requests merged in 2023-01, with the labels that each got.

#3154 keep social avatar update order also for background job
  lib/Service/SocialApiService.php
Labels: bug, 4. to release, backport-request

#3157 fix: double scrollbar in details pane
  css/contacts.scss
  src/components/ContactDetails.vue
Labels: bug, 3. to review, design, backport-request

#3158 ci: delete node workflow
  .github/workflows/node.yml
Labels: 3. to review, technical debt

#3152 use Mastodon API instead of scraping
  lib/Service/Social/MastodonProvider.php
  tests/unit/Service/Social/MastodonProviderTest.php
Labels: bug, 3. to review

#3173 allow social avatars from telegram, fixes #2393
  lib/Service/Social/CompositeSocialProvider.php
  lib/Service/Social/TelegramProvider.php
  src/components/ContactDetails/ContactDetailsAvatar.vue
  tests/unit/Service/Social/TelegramProviderTest.php
Labels: enhancement, 4. to release

#3185 ci: trigger fixup workflow on push
  .github/workflows/fixup.yml
Labels: 3. to review

#3187 perf(autoloader): Use Composer's authoritative classmap
  composer.json
  composer/autoload.php
Labels: 3. to review, performance

#3164 chore: drop support for PHP 7.4
  .github/workflows/lint-php.yml
  .github/workflows/phpunit.yml
  composer.json
  composer.lock
  lib/ContactsMenu/Providers/DetailsProvider.php
  lib/Controller/ContactsController.php
  lib/Cron/SocialUpdateRegistration.php
  lib/Service/Social/CompositeSocialProvider.php
  lib/Service/Social/DiasporaProvider.php
  lib/Service/Social/FacebookProvider.php
  lib/Service/Social/InstagramProvider.php
  lib/Service/Social/MastodonProvider.php
  lib/Service/Social/XingProvider.php
  lib/Service/SocialApiService.php
  tests/unit/ContactsMenu/Provider/DetailsProviderTest.php
  tests/unit/Service/ImageResizerTest.php
  tests/unit/Service/Social/DiasporaProviderTest.php
  tests/unit/Service/Social/FacebookProviderTest.php
  tests/unit/Service/Social/InstagramProviderTest.php
  tests/unit/Service/Social/MastodonProviderTest.php
  tests/unit/Service/Social/XingProviderTest.php
  tests/unit/Service/SocialApiServiceTest.php
Labels: 3. to review

#3196 [stable5.0] chore(deps): bump @mattkrick/sanitize-svg from 0.3.1 to 0.4.0
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#3199 fix: mime case matching
  src/models/contact.js
Labels: bug, 3. to review, backport-request

#3202 v5.0.3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#3203 v4.2.4
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#3204 chore: forward port changelogs of v4.2.4 and v5.0.3
  CHANGELOG.md
Labels: 3. to review
