Repository nextcloud/contacts, pull requests merged in 2023-07, with the labels that each got.

#3485 ci(xmllint): bump xmllint-action to v1.1
  .github/workflows/lint-info-xml.yml
Labels: 3. to review, backport-request

#3500 chore: Add PR feedback automation
  .github/workflows/pr-feedback.yml
Labels: 3. to review

#3493 fix(contacts): split up detailed-name again to fix vCard
  src/models/rfcProps.js
Labels: bug, 4. to release, design, regression

#3527 fix import loads forever
  src/components/AppNavigation/Settings/SettingsImportContacts.vue
Labels: bug, 3. to review, skill:frontend

#3505 deactivate social avatars from twitter
  img/twitter.svg
  lib/Service/Social/CompositeSocialProvider.php
  lib/Service/Social/TelegramProvider.php
  lib/Service/Social/TwitterProvider.php
  tests/unit/Service/Social/TelegramProviderTest.php
  tests/unit/Service/Social/TwitterProviderTest.php
Labels: 3. to review, compatibility, regression

#3504 change Mastodon tree for social avatar
  lib/Service/Social/MastodonProvider.php
  tests/unit/Service/Social/MastodonProviderTest.php
Labels: bug, 3. to review
