Repository nextcloud/contacts, pull requests merged in 2024-07, with the labels that each got.

#4007 fix(deps)!: drop nextcloud 29 support
  .github/workflows/phpunit.yml
  appinfo/info.xml
Labels: 3. to review

#4010 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#4012 fix: long contact name overlapping with other content
  src/components/ContactDetails.vue
Labels: bug, 3. to review

#4013 feat: show loading icon when deleting or renaming groups
  src/components/AppNavigation/GroupNavigationItem.vue
Labels: enhancement, 4. to release

#3987 [stable6.0] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4035 fix: redesign seetings toggle to Nextcloud 30 style
  src/components/AppNavigation/RootNavigation.vue
Labels: 3. to review, design

#4036 chore: npm run lint:fix
  src/components/AppNavigation/CircleNavigationItem.vue
  src/components/AppNavigation/GroupNavigationItem.vue
  src/models/contact.js
  src/store/circles.js
  src/store/contacts.js
Labels: 3. to review, technical debt

#4040 ContactsList: remove top margin to align with the navigation sidebar
  src/components/ContactsList.vue
Labels: 3. to review

#4041 fix: adjust spacing and alignment in the contact details view
  src/components/ContactDetails.vue
  src/components/DetailsHeader.vue
  src/css/ContactDetailsLayout.scss
Labels: 3. to review, design

#4042 style(ContactsListItem): fix subtitle
  src/components/ContactsList/ContactsListItem.vue
Labels: 4. to release

#4039 Address book settings: style changes and add NcTextField
  src/components/AppNavigation/Settings/SettingsAddressbook.vue
  src/components/AppNavigation/Settings/SettingsNewAddressbook.vue
Labels: 3. to review

#4045 fix: responsiveness for contacts details
  src/components/CircleDetails.vue
  src/components/DetailsHeader.vue
  src/components/Properties/PropertyMultipleText.vue
  src/components/Properties/PropertyText.vue
  src/css/Properties/Properties.scss
  src/css/contacts.scss
Labels: bug, 3. to review, design

#4048 chore: release v6.1.0-alpha.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#3963 enh/Improve group adding
  src/components/AppNavigation/GroupNavigationItem.vue
  src/components/AppNavigation/RootNavigation.vue
  src/components/EntityPicker/ContactsPicker.vue
  src/components/EntityPicker/EntityPicker.vue
Labels: enhancement, 3. to review

#4049 ci: update app store build and publish workflow
  .github/workflows/appstore-build-publish.yml
Labels: 3. to review

#4060 ContactsListItem: make horizontal and vertical padding equal
  src/components/ContactsList/ContactsListItem.vue
Labels: 3. to review

#4061 chore: release v6.1.0-alpha.2
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review
