Repository nextcloud/contacts, pull requests merged in 2024-04, with the labels that each got.

#3859 chore(CI): Adjust testing matrix for Nextcloud 29 on main
  .github/workflows/phpunit.yml
Labels: backport-request

#3864 Fix: open import contacts filePicker
  src/components/AppNavigation/Settings/SettingsImportContacts.vue
Labels: bug, 3. to review, regression

#3862 chore(vue3): migrate deprecated slot syntax
  src/components/AppNavigation/CircleNavigationItem.vue
  src/components/AppNavigation/GroupNavigationItem.vue
  src/components/AppNavigation/Settings/SettingsImportContacts.vue
  src/components/CircleDetails.vue
  src/components/ContactDetails.vue
  src/components/MembersList/MembersListItem.vue
  src/components/Properties/PropertyGroups.vue
Labels: 3. to review, technical debt

#3861 add signal messenger option, order list alphabetically
  src/models/rfcProps.js
Labels: 3. to review, backport-request

#3870 Revert "[stable6.0] feat(deps): Add nextcloud 30 support"
  appinfo/info.xml
Labels: 3. to review

#2466 Implement Drag and Drop feature for adding contacts to group
  src/components/AppNavigation/GroupNavigationItem.vue
  src/components/ContactsList/ContactsListItem.vue
  src/store/index.js
Labels: enhancement, 3. to review

#3879 chore(CI): add summary step
  .github/workflows/phpunit.yml
Labels: 3. to review

#3888 Release v6.0.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: enhancement, 3. to review

#3889 chore(CI) : adjust testing matrix for Nextcloud stable29
  .github/workflows/phpunit.yml
Labels: 3. to review

#3894 Fix: Changelog for v6.0.O
  CHANGELOG.md
Labels: 3. to review

#3899 fix(settings): clarify settings option for open team
  src/models/constants.ts
Labels: 3. to review, papercut, feature: circles
