Repository nextcloud/contacts, pull requests merged in 2024-01, with the labels that each got.

#3766 chore(vue3): migrate event buses to mitt
  package-lock.json
  package.json
  src/components/AppContent/ContactsContent.vue
  src/components/ContactDetails.vue
  src/components/ContactDetails/ContactDetailsAddNewProp.vue
  src/components/ContactDetails/ContactDetailsAvatar.vue
  src/components/ContactDetails/ContactDetailsProperty.vue
  src/components/ContactsList/ContactsListItem.vue
  src/components/Properties/PropertyTitle.vue
Labels: 3. to review, technical debt

#3760 Remove empty content when at least one related resrouce exists.
  src/components/ContactDetails.vue
Labels: bug, 4. to release

#3768 Release v5.5.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#3777 Drop Nextcloud 25 support
  .github/workflows/phpunit.yml
  appinfo/info.xml
Labels: enhancement, 3. to review, backport-request

#3358 Add NOTES and RELATED to search properties
  src/models/contact.js
Labels: enhancement, 3. to review

#3759 Add confirmation dialog before importing contacts
  src/components/ConfirmationDialog.vue
  src/files-action.js
Labels: 3. to review
