Repository nextcloud/contacts, pull requests merged in 2024-06, with the labels that each got.

#3949 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#3955 Update icon work
  .reuse/dep5
  img/app.svg
  img/contacts.svg
  img/favicon-mask.svg
  img/favicon-touch.png
  img/favicon-touch.svg
  img/favicon.ico
  img/favicon.png
  img/favicon.svg
  img/group.svg
Labels: 4. to release, design

#3804 perf: migrate to vite
  .eslintrc.cjs
  .gitignore
  babel.config.cjs
  jest.config.cjs
  lib/Controller/PageController.php
  lib/Listener/LoadContactsFilesActions.php
  package-lock.json
  package.json
  src/admin-settings.js
  src/components/AppNavigation/Settings/SettingsAddressbook.vue
  src/components/ContactDetails.vue
  src/components/DetailsHeader.vue
  src/css/ContactDetailsLayout.scss
  src/css/ContactsListItem.scss
  src/css/ImportScreen.scss
  src/css/Properties/Properties.scss
  src/css/Settings/SettingsAddressbookSharee.scss
  src/css/Settings/SettingsAddressbookShares.scss
  src/css/SettingsSection.scss
  src/css/animations.scss
  src/css/contacts.scss
  src/files-action.js
  src/main.js
  src/mixins/CircleActionsMixin.js
  src/services/cdav.js
  src/services/collaborationAutocompletion.js
  stylelint.config.cjs
  templates/settings/admin.php
  vite.config.js
Labels: 4. to release, performance

#3995 chore(l10n): add translator context to manager
  src/models/rfcProps.js
Labels: 3. to review

#3994 chore: remove dead file action condition
  src/files-action.js
Labels: 3. to review, technical debt
