Repository nextcloud/contacts, pull requests merged in 2024-03, with the labels that each got.

#3834 Release 6.0.0-alpha.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: enhancement, 3. to review

#3836 [stable5.5] fix(settings): Fix focus trap preventing addressbook rename
  package-lock.json
  package.json
Labels: bug, 3. to review, regression

#3831 feat: Implement team overview page updates
  package-lock.json
  package.json
  src/components/AppContent/CircleContent.vue
  src/components/CircleDetails.vue
  src/components/Icons/IconCircles.vue
  src/components/MembersList/MembersListItem.vue
Labels: enhancement, 3. to review

#3840 Release v5.5.3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: enhancement, 3. to review

#3846 chore(vue3): migrate ::v-deep to :deep
  src/components/AppNavigation/RootNavigation.vue
  src/components/AppNavigation/Settings/SettingsAddressbookSharee.vue
  src/components/AppNavigation/Settings/SettingsImportContacts.vue
  src/components/ContactDetails.vue
  src/components/ContactDetails/ContactDetailsAvatar.vue
  src/components/DetailsHeader.vue
  src/components/EntityPicker/EntityBubble.vue
  src/components/EntityPicker/EntityPicker.vue
  src/components/EntityPicker/EntitySearchResult.vue
  src/components/EntityPicker/NewCircleIntro.vue
  src/components/MemberList.vue
  src/components/ProcessingScreen.vue
Labels: 3. to review, technical debt

#3851 Release v6.0.0-rc1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: enhancement, 3. to review
