Repository nextcloud/contacts, pull requests merged in 2024-12, with the labels that each got.

#4238 fix(release): Fix wget output option
  .github/workflows/appstore-conventional-build-publish.yml
Labels: 3. to review

#4249 fix: check if photo property is set before downloading
  src/components/ContactsList/ContactsListItem.vue
  src/models/contact.js
Labels: 3. to review, backport-request

#4194 feat: create a read-only contactdetails component
  lib/AppInfo/Application.php
  lib/Event/LoadContactsOcaApiEvent.php
  lib/Listener/LoadContactsOcaApi.php
  src/oca.js
  src/oca/mountContactDetails.js
  src/views/ReadOnlyContactDetails.vue
  vite.config.js
Labels: 4. to release

#4253 fix: convert pre-commit.js to ES module
  build/pre-commit.js
Labels: bug, 3. to review

#4257 chore: rename pre-commit.cjs in workflow
  .github/workflows/appstore-conventional-build-publish.yml
Labels: 3. to review

#4259 chore(Changelog.md): Add spdx header
  CHANGELOG.md
Labels: 3. to review, backport-request

#4263 Chore: undo failed releases
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#4264 chore: Revert "chore(release): v6.1.2 [skip ci]"
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#4268 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies
