Repository nextcloud/contacts, pull requests merged in 2024-08, with the labels that each got.

#4073 fix(CircleDetails): Improve calculation of member list
  src/components/CircleDetails.vue
Labels: 3. to review, feature: circles

#4076 fix(Members): Rename 'Contact groups' to 'groups'
  src/models/constants.ts
Labels: 3. to review, feature: circles, backport-request

#4075 fix(MemberList): Don't use VirtualList for listing members
  src/components/AppNavigation/CircleNavigationItem.vue
  src/components/MemberList.vue
  src/components/MembersList/MembersListItem.vue
Labels: 3. to review, feature: circles, backport-request

#4079 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4071 [stable6.0] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4070 [stable5.5] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4086 chore: `npm run lint:fix`
  src/components/AppNavigation/GroupNavigationItem.vue
  src/components/AppNavigation/RootNavigation.vue
Labels: 3. to review, technical debt

#4084 fix: scrollable button in navigation
  src/components/AppNavigation/RootNavigation.vue
Labels: bug, 3. to review, skill:frontend

#4098 Hello coding-standard 1.2.3
  .git-blame-ignore-revs
  .nextcloudignore
  composer.lock
  lib/Service/Social/MastodonProvider.php
  lib/Service/Social/TelegramProvider.php
  lib/Service/SocialApiService.php
  lib/Settings/AdminSettings.php
  tests/unit/ContactsMenu/Provider/DetailsProviderTest.php
  tests/unit/Controller/ContactsControllerTest.php
  tests/unit/Controller/PageControllerTest.php
  tests/unit/Service/Social/DiasporaProviderTest.php
  tests/unit/Service/Social/FacebookProviderTest.php
  tests/unit/Service/Social/GravatarProviderTest.php
  tests/unit/Service/Social/InstagramProviderTest.php
  tests/unit/Service/Social/MastodonProviderTest.php
  tests/unit/Service/Social/TelegramProviderTest.php
  tests/unit/Service/Social/XingProviderTest.php
  tests/unit/Service/SocialApiServiceTest.php
Labels: 3. to review, technical debt

#4096 "Line" manager
  src/models/rfcProps.js
Labels: enhancement, 3. to review, design, feature: contacts, feature: organization chart

#4093 chore(release): v6.1.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#4100 fix: update wrong release date
  CHANGELOG.md
Labels: 3. to review
