Repository nextcloud/contacts, pull requests merged in 2024-10, with the labels that each got.

#4155 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4176 fix:filepicker for contact avatar
  src/components/ContactDetails/ContactDetailsAvatar.vue
Labels: bug, 3. to review

#4173 fix: support for RFC 6474
  src/models/rfcProps.js
Labels: 3. to review

#4092 PropertySelect: hide PropertySelects with only one selectable option
  src/components/Properties/PropertySelect.vue
Labels: 3. to review

#4191 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4199 feat: add support for webp contact avatars
  src/components/ContactDetails/ContactDetailsAvatar.vue
Labels: enhancement, 3. to review

#4204 Chore/transifex stable
  .tx/backport
  REUSE.toml
Labels: enhancement, 3. to review

#4205 chore: stale workflow
  .github/stale.yml
  .github/workflows/stale.yml
Labels: enhancement, 3. to review
