Repository nextcloud/contacts, pull requests merged in 2024-09, with the labels that each got.

#4025 chore: update workflows from templates
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node-test.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/reuse.yml
Labels: 3. to review, dependencies, automated

#4107 GroupNavigationItem: encode exported contact groups as UTF-8
  src/components/AppNavigation/GroupNavigationItem.vue
Labels: 3. to review, backport-request

#3978 chore(renovate): ignore dependencies related to vue 3
  renovate.json
Labels: 3. to review

#4088 [stable5.5] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4089 [stable6.0] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4116 chore(renovate): distribute reviews to all maintainers
  renovate.json
Labels: 3. to review

#4118 Migrate REUSE to toml format
  .reuse/dep5
  REUSE.toml
Labels: 3. to review, technical debt

#4124 chore: Update code owners
  .github/CODEOWNERS
Labels: 3. to review

#4146 chore(Npm Audit Fix): update create pull request dependency
  .github/workflows/npm-audit-fix.yml
Labels: 3. to review

#4154 fix: remove prop mutation
  src/components/Properties/PropertyGroups.vue
Labels: bug, 3. to review, regression

#4108 fix: respect advanced group sharing settings in frontend
  lib/Controller/PageController.php
  lib/Service/GroupSharingService.php
  src/components/AppNavigation/Settings/SettingsAddressbookShare.vue
  tests/unit/Controller/PageControllerTest.php
  tests/unit/Service/GroupSharingServiceTest.php
Labels: bug, 3. to review, feature: contacts, backport-request

#4167 chore(php-cs-fixer): ignore node_modules
  .php-cs-fixer.dist.php
Labels: 3. to review, technical debt
