Repository nextcloud/contacts, pull requests merged in 2024-05, with the labels that each got.

#3910 Replace "Add members" with "Manage members" in team's dashboards
  src/components/CircleDetails.vue
Labels: 3. to review, feature: circles

#3924 ci: Create npm-audit-fix.yml
  .github/workflows/npm-audit-fix.yml
Labels: 3. to review

#3925 chore: create renovate
  .github/dependabot.yml
  renovate.json
Labels: 3. to review

#3932 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#3933 [stable6.0] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#3900 Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#3901 Updating appstore-build-publish.yml workflow from template
  .github/workflows/appstore-build-publish.yml
Labels: dependencies

#3931 [stable5.5] Fix npm audit
  .github/workflows/phpunit.yml
  package-lock.json
Labels: 3. to review, dependencies

#3757 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node-test.yml
  .github/workflows/pr-feedback.yml
Labels: 3. to review, dependencies, automated

#3946 chore: npm run stylelint:fix
  src/components/AppContent/CircleContent.vue
  src/components/AppContent/ContactsContent.vue
  src/components/AppNavigation/RootNavigation.vue
  src/components/AppNavigation/Settings/SettingsAddressbook.vue
  src/components/AppNavigation/Settings/SettingsAddressbookSharee.vue
  src/components/AppNavigation/Settings/SettingsNewAddressbook.vue
  src/components/CircleDetails.vue
  src/components/ContactDetails.vue
  src/components/ContactDetails/ContactDetailsAvatar.vue
  src/components/DetailsHeader.vue
  src/components/EntityPicker/EntityPicker.vue
  src/components/EntityPicker/EntitySearchResult.vue
  src/components/EntityPicker/NewCircleIntro.vue
  src/components/MemberList.vue
Labels: 3. to review
