Repository nextcloud/contacts, pull requests merged in 2025-05, with the labels that each got.

#4444 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4432 [stable7.0] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4461 Revert "chore(deps-dev): bump vite from 5.4.19 to 6.3.4"
  package-lock.json
  package.json
Labels: 3. to review, regression

#4462 chore(release): v7.1.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#4464 fix: center align rows
  src/css/Properties/Properties.scss
Labels: bug, 4. to release, regression, backport-request

#4475 chore(tests): Cleanup bootstrap.php to be forward-compatible
  tests/bootstrap.php
Labels: 3. to review
