Repository nextcloud/contacts, pull requests merged in 2025-03, with the labels that each got.

#4371 chore(reuse): add to changelog.md
  CHANGELOG.md
Labels: 3. to review

#4345 [stable7.0] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4216 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4374 Move changelog license header to a separate file
  CHANGELOG.md
  CHANGELOG.md.license
Labels: 3. to review, backport-request

#4378 [stable7.0] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4384 chore(release): v6.0.4
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#4385 chore: add changelog title
  CHANGELOG.md
Labels: 3. to review, regression

#4386 chore: add changelog title
  CHANGELOG.md
Labels: 3. to review, regression

#4369 feat: add support for avif contact avatars
  src/components/ContactDetails/ContactDetailsAvatar.vue
Labels: enhancement, 3. to review

#4394 fix: Instantiation of ContactsManager
  lib/Service/SocialApiService.php
  tests/unit/Service/SocialApiServiceTest.php
Labels: bug, 3. to review, php

#4401 Use css variables instead of magic numbers
  src/components/AppNavigation/Settings/SettingsAddressbook.vue
  src/components/AppNavigation/Settings/SettingsAddressbookShare.vue
  src/components/ContactDetails.vue
  src/components/ContactsList.vue
  src/components/ContactsList/ContactsListItem.vue
  src/components/Properties/PropertyTitle.vue
  src/css/ContactDetailsLayout.scss
  src/css/Settings/SettingsAddressbookSharee.scss
  src/css/Settings/SettingsAddressbookShares.scss
  src/css/contacts.scss
Labels: 3. to review
