Repository nextcloud/contacts, pull requests merged in 2025-02, with the labels that each got.

#4322 fix: show error on empty group name
  src/components/AppNavigation/RootNavigation.vue
Labels: bug, 3. to review, backport-request

#4312 chore: backport translations to stable7.0
  .tx/backport
Labels: 3. to review

#4323 [stable7.0] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4330 chore(release): v7.0.0-rc.2
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#4331 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#4334 fix: Make circle members visible again by moving them out of the modal
  src/components/AppContent/CircleContent.vue
  src/components/CircleDetails.vue
  src/components/DetailsHeader.vue
  src/components/MemberList/MemberList.vue
  src/components/MemberList/MemberListGroup.vue
  src/components/MemberList/MemberListItem.vue
  src/models/constants.ts
  src/models/contact.js
  tsconfig.json
Labels: bug, 3. to review

#4339 release v6.0.3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#4348 chore(release): v7.0.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review
