Repository nextcloud/contacts, pull requests merged in 2025-09, with the labels that each got.

#4702 chore(release): v7.3.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#4713 chore: add psalm
  .github/workflows/psalm-matrix.yml
  .gitignore
  composer.json
  composer.lock
  lib/AppInfo/Application.php
  lib/Capabilities.php
  lib/ContactsMenu/Providers/DetailsProvider.php
  lib/Cron/SocialUpdate.php
  lib/Cron/SocialUpdateRegistration.php
  lib/Listener/LoadContactsFilesActions.php
  lib/Listener/LoadContactsOcaApi.php
  lib/Service/Social/DiasporaProvider.php
  lib/Service/Social/FacebookProvider.php
  lib/Service/Social/GravatarProvider.php
  lib/Service/Social/InstagramProvider.php
  lib/Service/Social/MastodonProvider.php
  lib/Service/Social/TelegramProvider.php
  lib/Service/Social/TumblrProvider.php
  lib/Service/Social/XingProvider.php
  lib/Service/SocialApiService.php
  lib/Settings/AdminSettings.php
  phpunit.xml
  psalm.xml
  tests/psalm-baseline.xml
  tests/psalm-baseline.xml.license
  tests/unit/Service/SocialApiServiceTest.php
  vendor-bin/psalm/composer.json
  vendor-bin/psalm/composer.json.license
  vendor-bin/psalm/composer.lock
  vendor-bin/psalm/composer.lock.license
Labels: 3. to review, technical debt

#4722 fix: do not allow to exclude system accounts from the bday calendar
  src/components/ContactDetails.vue
Labels: bug, 3. to review, feature: contacts, backport-request

#4728 fix: detect addressbook ACL's properly
  src/components/ContactDetails.vue
  src/store/addressbooks.js
Labels: 3. to review, backport-request

#4747 fix: rename circle to team for clarity
  src/components/MemberList/MemberList.vue
Labels: 3. to review

#4746 fix(SettingsAddressbook): prevent sharing an addressbook that has been shared with you
  src/components/AppNavigation/Settings/SettingsAddressbook.vue
Labels: 3. to review

#4643 Implement addressbook sorting
  package-lock.json
  package.json
  src/components/ContactDetails.vue
  src/models/contact.js
  src/store/addressbooks.js
  src/utils/addressbookUtils.js
  tests/javascript/store/addressbooks.test.js
Labels: 3. to review

#4727 [stable8.0] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies
