Repository nextcloud/contacts, pull requests merged in 2025-04, with the labels that each got.

#4412 refactor: use server container for contacts manager
  lib/Service/SocialApiService.php
  tests/unit/Service/SocialApiServiceTest.php
Labels: 3. to review, backport-request

#4377 Combine bday and deathdate
  src/components/ContactDetails.vue
  src/components/Properties/PropertyTitle.vue
Labels: enhancement, 4. to release, feature: contacts

#4390 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4419 chore: add support for php 8.4 in composer
  composer.json
Labels: 3. to review

#4421 chore: only support stable7.0
  .github/workflows/npm-audit-fix.yml
  .tx/backport
Labels: 3. to review

#4422 chore(ci): revive php-cs-fixer
  .github/workflows/lint-php-cs.yml
  composer.json
Labels: 3. to review, backport-request

#4425 fix(lint-php-cs): use minimum available php version
  .github/workflows/lint-php-cs.yml
Labels: 3. to review, backport-request

#4418 chore(devtools): enable devtools
  src/main.js
Labels: 3. to review, backport-request

#4424 Feat: handle invalid email
  package-lock.json
  package.json
  src/components/ContactDetails.vue
  src/components/Properties/PropertyText.vue
  src/css/Properties/Properties.scss
Labels: enhancement, 3. to review

#4380 Adding error on invalid email-address for contact-editor
  package-lock.json
  package.json
  src/components/Properties/PropertyText.vue
  src/css/Properties/Properties.scss
Labels: enhancement, 2. developing, feedback-requested

#4433 fix: update store state after addressbook change
  src/components/ContactDetails.vue
  src/store/addressbooks.js
  src/store/contacts.js
  src/store/groups.js
Labels: bug, 3. to review

#3686 ci: Add node build job
  .github/workflows/node.yml
Labels: 3. to review

#4437 chore(release): v7.1.0-rc.1
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#4443 Fix contact groups property title not displayed
  src/components/Properties/PropertyTitle.vue
Labels: 3. to review

#4445 fix: use @nextcloud/moment for automatic locale detection/import
  src/components/Properties/PropertyDateTime.vue
Labels: bug, 3. to review, backport-request

#4315 chore(CI): Updating npm-audit-fix.yml workflow from template
  .github/workflows/npm-audit-fix.yml
Labels: dependencies

#4261 fix: specify origin of request when search for users
  src/services/collaborationAutocompletion.js
Labels: bug, 3. to review

#4442 fix: do not load disabled address books
  src/components/AppNavigation/Settings/SettingsAddressbook.vue
  src/views/Contacts.vue
Labels: 3. to review, backport-request
