Repository nextcloud/contacts, pull requests merged in 2025-08, with the labels that each got.

#4602 make rtl checks error level and apply fixes
  src/components/ChartTemplate.vue
  src/components/CircleDetails.vue
  stylelint.config.cjs
Labels: bug, enhancement, 3. to review

#4607 fix(teams): Restore member management in new ui
  src/components/CircleDetails.vue
  src/components/MemberList/MemberGridItem.vue
  src/components/MemberList/MemberList.vue
Labels: 3. to review, feature: teams, skill:frontend

#4638 chore: release 7.3.0-rc.2
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#4639 chore: release v8.0.0-rc.1
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#4615 fix: routing based on base64 encoding
  lib/ContactsMenu/Providers/DetailsProvider.php
  lib/Controller/ContactsController.php
  src/components/AppContent/ChartContent.vue
  src/components/AppContent/ContactsContent.vue
  src/components/AppNavigation/GroupNavigationItem.vue
  src/components/ContactDetails/ContactDetailsProperty.vue
  src/components/ContactsList.vue
  src/components/ContactsList/ContactsListItem.vue
  src/mixins/RouterMixin.js
  src/models/contact.js
  src/views/Contacts.vue
  tests/unit/ContactsMenu/Provider/DetailsProviderTest.php
  tests/unit/Controller/ContactsControllerTest.php
Labels: bug, 3. to review, backport-request

#4645 fix: virtual contacts list scroller logic
  src/components/ContactsList.vue
Labels: bug, 3. to review, backport-request

#4646 ci: allow feats for main only
  .github/workflows/block-unconventional-commits.yml
Labels: enhancement, 3. to review, backport-request

#4648 chore: update main version and maintained versions
  .github/workflows/npm-audit-fix.yml
  .tx/backport
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#4653 chore: add test:unit:dev to composer commands
  composer.json
Labels: 3. to review

#4659 Fix changing addressbook of contact
  src/components/AppNavigation/RootNavigation.vue
  src/components/ContactsList.vue
Labels: 3. to review, backport-request

#4657 Use material symbol variant of delete icon
  src/components/AppNavigation/CircleNavigationItem.vue
  src/components/AppNavigation/GroupNavigationItem.vue
  src/components/AppNavigation/Settings/SettingsAddressbook.vue
  src/components/AppNavigation/Settings/SettingsAddressbookSharee.vue
  src/components/CircleDetails/CircleSettings.vue
  src/components/ContactDetails.vue
  src/components/ContactDetails/ContactDetailsAvatar.vue
  src/components/ContactsList.vue
  src/components/MemberList/MemberGridItem.vue
  src/components/MemberList/MemberListItem.vue
  src/components/Properties/PropertyActions.vue
  src/components/Properties/PropertyTitleIcon.vue
Labels: 3. to review, design
