Repository nextcloud/contacts, pull requests merged in 2025-06, with the labels that each got.

#4484 ci: update node.yml workflow from template
  .github/workflows/node.yml
Labels: dependencies

#4488 [stable7.1] chore(deps): bump tar-fs
  package-lock.json
Labels: 3. to review

#4490 chore: release v6.0.5
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#4492 fix: delete appstore-build-publish.yml
  .github/workflows/appstore-build-publish.yml
Labels: bug, 3. to review

#4493 ci: simplify release and automate pre-releases
  .github/workflows/appstore-conventional-build-publish.yml
Labels: 3. to review

#4496 [stable7.1] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4497 ci(phpunit): don't run in server master
  .github/workflows/phpunit.yml
Labels: 3. to review

#4501 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4500 [stable7.1] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4503 fix(contacts): add confirmation dialog when leaving a team
  src/components/MemberList/MemberListItem.vue
Labels: enhancement, 3. to review, feature: teams

#4520 chore: update php versions on issue template
  .github/ISSUE_TEMPLATE/bug_report_contacts.yml
Labels: enhancement, 3. to review

#4526 [Stable7.1]chore: npm audit fix
  package-lock.json
Labels: 3. to review

#4528 fix(groups): show hint about adding read-only contacts to contact groups
  src/components/EntityPicker/EntityPicker.vue
Labels: enhancement, 3. to review, backport-request

#4534 fix: fetch addressbook contacts when enabled
  src/store/addressbooks.js
Labels: bug, 3. to review, backport-request
