Repository nextcloud/contacts, pull requests merged in 2025-07, with the labels that each got.

#4477 Add multiactions in the contact list
  src/components/ContactsList.vue
  src/components/ContactsList/ContactsListItem.vue
Labels: enhancement, 3. to review

#4547 [stable7.1] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4552 chore(release): v7.2.0-rc.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: enhancement, 3. to review

#4554 chore: remove nextcloud 32 support
  appinfo/info.xml
Labels: 3. to review

#4560 chore(release): v7.2.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: enhancement, 3. to review

#4561 chore: drop support for stable7.1
  .github/workflows/npm-audit-fix.yml
  .tx/backport
Labels: enhancement, 3. to review

#4567 fix: rendering of phone numbers
  src/services/updateDesignSet.js
Labels: bug, 3. to review, backport-request

#4582 fix: always convert vcard photo urls to string
  src/models/contact.js
Labels: bug, 3. to review, backport-request

#4587 test: add a basic playwright e2e test
  .github/workflows/e2e-test.yml
  .gitignore
  jest.config.cjs
  package-lock.json
  package.json
  playwright.config.js
  src/components/ContactsList.vue
  tests/javascript/e2e/contact.spec.ts
  tests/javascript/e2e/login.ts
Labels: enhancement, 3. to review, backport-request

#4586 fix: missing getLocale import
  src/components/Properties/PropertyDateTime.vue
Labels: bug, 3. to review, backport-request

#4579 chore(deps): replace @shortcm/qr-image with qreator
  package-lock.json
  package.json
  src/components/ContactDetails.vue
Labels: 3. to review, technical debt, dependencies

#4563 chore: drop obsolete vue-click-outside dependency
  package-lock.json
  package.json
  src/components/ContactDetails/ContactDetailsAvatar.vue
  src/main.js
  src/oca/mountContactDetails.js
Labels: 4. to release, technical debt, dependencies
